version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-cotiza360
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-cotiza360
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # consumer externo
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # DOS LISTENERS: interno (Docker) y externo (host)
      KAFKA_ADVERTISED_LISTENERS: |
        PLAINTEXT://kafka:29092,
        PLAINTEXT_HOST://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: postgres:14
    container_name: postgres-cotiza360
    environment:
      POSTGRES_USER: cotiza360_user
      POSTGRES_PASSWORD: tu_password_seguro
      POSTGRES_DB: cotiza360_db
      PGDATA: /data/postgres
    volumes:
      - postgres-cotiza360:/data/postgres
    ports:
      - "5432:5432"

  api:
    container_name: cotiza360-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - kafka
    environment:
      DATABASE_URL: postgresql://cotiza360_user:tu_password_seguro@postgres:5432/cotiza360_db?schema=public
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "5555:5555"
    command: >
      sh -c "npm install &&
             npx prisma migrate deploy &&
             npx prisma generate &&
             npm run start:dev"

volumes:
  postgres-cotiza360:
    name: postgres-cotiza360-data
